#This is the docker compose file. This sets up the docker container we need.

#Please contact Arun (arun8r@gmail.com) if you have any questions.

#Last remark: Don't change this file unless you know what you're doing.


web:
    image: arun8r/djmodwsgi #Same image as above.
    
    volumes:
      - "$PWD:/app"

    ports:
      - "8000:8000"        #Expose port 8000 on your machine to port 8000 of the docker container. Eventually, clients will connect to port 8000
                           #of the server and they will be displayed whatever is coming out of port 8000 on your computer. in your browser or POSTMAN, 
                           #this allows you to access port 8000 of the docker container at localhost:8000.

    command: bash -c "mod_wsgi-express start-server --port 8000 --working-directory /app/web --url-alias /static /app/web/static --reload-on-changes /app/web/web/wsgi.py" 
