sudo: required

dist: trusty

language: python
python:
  - "3.5"

services:
  - docker

before_install:
 - docker pull arun8r/djmodwsgi
 
before_script:
 - docker-compose -f ./vote/vote_1register/docker-compose.yml up -d

script:
  -  docker exec -it vote1register_web_1 bash -c "cd web && bash ./tests.sh"
  -  docker exec -it vote1register_proc_1 bash -c "cd proc && bash ./tests.sh"

after_script:
 - docker-compose -f ./vote/vote_1register/docker-compose.yml stop
 - docker-compose -f ./vote/vote_1register/docker-compose.yml rm y