sudo: required

dist: trusty

language: python
python:
  - "3.5"

services:
  - docker

before_install:
 - docker pull arun8r/djmodwsgi
 
before_script:
 - docker-compose -f ./vote/vote_1register/docker-compose.yml up

script:
  - bash ./vote/test.sh

after_script:
 - docker-compose -f ./vote/vote_1register/docker-compose.yml stop
 - docker-compose -f ./vote/vote_1register/docker-compose.yml rm 