sudo: required

dist: trusty

services:
  - docker

before_install:
 - docker pull arun8r/djmodwsgi
 
before_script:
 - docker-compose -f ./vote/vote_1register/docker-compose.yml up -d
 - docker-compose -f ./vote/vote_2cast/docker-compose.yml up -d 

script:
  -  docker exec -it vote1register_web_1 bash -c "cd vote/vote_1register/web && bash ./tests.sh"
  -  docker exec -it vote2cast_web_1 bash -c "cd vote/vote_2cast/web && bash ./tests.sh"

after_script:
 - docker-compose -f ./vote/vote_1register/docker-compose.yml stop
 - docker-compose -f ./vote/vote_1register/docker-compose.yml -f
 - docker-compose -f ./vote/vote_2cast/docker-compose.yml stop
 - docker-compose -f ./vote/vote_2cast/docker-compose.yml -f 