#Please contact Arun (arun8r@gmail.com) if you have any questions.

printer:
    image: arun8r/djmodwsgi:latest #Same image as above.
    
    volumes:
      - "$PWD:/app"
      - /dev/bus/usb:/dev/bus/usb

    privileged: true

    command: bash -c "python /app/print.py"
